// Generated by https://quicktype.io

export interface SortOptions {
  sortOptions: SortOption[];
  meta: Meta;
  links: any[];
}

export interface Meta {
  dataSource: string;
  extractDate: string;
  itemCount: number;
  returncode: null;
  totalCount: number;
  totalPages: number;
  pageSize: number;
  pageNumber: number;
}

export interface SortOption {
  sortOptionId: number;
  sortOptionName: string;
  sortOptionKey: string;
  links: any[];
}

export const sortOptionsResponse: SortOptions = {
  sortOptions: [
    {
      sortOptionId: 1,
      sortOptionName: 'Relevance',
      sortOptionKey: 'Relevance',
      links: [],
    },
    {
      sortOptionId: 2,
      sortOptionName: 'Rating (highest to lowest)',
      sortOptionKey: 'rating',
      links: [],
    },
    {
      sortOptionId: 3,
      sortOptionName: 'Rating (lowest to highest)',
      sortOptionKey: 'desc_rating',
      links: [],
    },
    {
      sortOptionId: 4,
      sortOptionName: 'Name (A to Z)',
      sortOptionKey: 'alpha',
      links: [],
    },
    {
      sortOptionId: 5,
      sortOptionName: 'Name (Z to A)',
      sortOptionKey: 'desc_alpha',
      links: [],
    },
    {
      sortOptionId: 10,
      sortOptionName: 'Distance',
      sortOptionKey: 'Distance',
      links: [],
    },
  ],
  meta: {
    dataSource: 'API',
    extractDate: '0001-01-01T00:00:00',
    itemCount: 0,
    returncode: null,
    totalCount: 6,
    totalPages: 1,
    pageSize: 6,
    pageNumber: 1,
  },
  links: [],
};
